### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by mardb** [ergon-project/FrontEnd#4]
Footer will need more Needs more
i.e.
 contacts us, 
careers
donate
connect with us 

etc...

**Comment by zer0kool** [comment]
Bet this is the oldest issues of all times. should git pull and fix it?

**Comment by mardb** [comment]
nah! lol 
    On Monday, July 13, 2020, 11:22:25 PM PDT, Alejandro Loaiza <notifications@github.com> wrote:  
 
 


Bet this is the oldest issues of all times. should git pull and fix it?

**Comment by mardb** [comment]
wow

    On Monday, July 20, 2020, 12:19:57 PM PDT, Alejandro Loaiza <notifications@github.com> wrote:  
 
 


Closed #4.
